version: '3'
services:
  database:
    image: bitnami/mysql:latest
    ports:
      - 3306:3306/tcp
    environment:
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=ignite_call
